name: GitHub Actions Demo
on:
  push:
    branches:
    - main
    paths-ignore:
    - .github/**
  pull_request:
    branches:
    - main
  schedule:
  - cron: 15 6 * * 0
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo event_name=${{ github.event_name }}
    - run: echo branch=${{ github.ref }}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - run: ls -lAR
  test:
    name: Test
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - run: echo Testing...
  load-test:
    name: Load-Test
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - run: echo Testing... && sleep 15
  production:
    name: Production
    if: inputs.environment == 'Production'
    runs-on: ubuntu-latest
    needs:
    - test
    - load-test
    steps:
    - run: echo Step x deploying... && sleep 10
    - run: echo Step x deploying... && sleep 10
    - run: echo Step x deploying... && sleep 10
    - run: echo Step x deploying... && sleep 10
    - run: echo Step x deploying... && sleep 10
