name: GitHub Actions Demo
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: 15 6 * * 6
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo event_name=${{ github.event_name }}
    - run: echo branch=${{ github.ref }}
